/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _APP_H_RPCGEN
#define _APP_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct wejscie {
	char wejscie[512];
};
typedef struct wejscie wejscie;

struct wyjscie {
	char wyjscie[512];
};
typedef struct wyjscie wyjscie;

#define WIADOMOSCPROG 0x21000000
#define WIADOMOSCVER 1

#if defined(__STDC__) || defined(__cplusplus)
#define KONWERTUJ 1
extern  void * konwertuj_1(wejscie *, CLIENT *);
extern  void * konwertuj_1_svc(wejscie *, struct svc_req *);
#define ODBIERZ 2
extern  wyjscie * odbierz_1(void *, CLIENT *);
extern  wyjscie * odbierz_1_svc(void *, struct svc_req *);
extern int wiadomoscprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define KONWERTUJ 1
extern  void * konwertuj_1();
extern  void * konwertuj_1_svc();
#define ODBIERZ 2
extern  wyjscie * odbierz_1();
extern  wyjscie * odbierz_1_svc();
extern int wiadomoscprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_wejscie (XDR *, wejscie*);
extern  bool_t xdr_wyjscie (XDR *, wyjscie*);

#else /* K&R C */
extern bool_t xdr_wejscie ();
extern bool_t xdr_wyjscie ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_APP_H_RPCGEN */
