/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "app.h"

char bufor[512];

void *
konwertuj_1_svc(wejscie *argp, struct svc_req *rqstp)
{
	static char * result;

	/*
	 * insert server code here
	 */
	bzero(bufor, 512);
	int j = 0;
    int i = 0;
    while (argp->wejscie[j] != '\0') {
		sprintf((char *) (bufor + i), "%02X", argp->wejscie[j]);
		j += 1;
		i += 2;
		}
	bufor[i++] = '\0';
	printf("Konwersja: %s -> %s\n", argp->wejscie, bufor);
	
	return (void *) &result;
}

wyjscie *
odbierz_1_svc(void *argp, struct svc_req *rqstp)
{
	static wyjscie  result;

	/*
	 * insert server code here
	 */
	strcpy(result.wyjscie, bufor);
	bzero(bufor, 512);
	return &result;
}
