/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "app.h"

wyjscie *
obliczenia_1_svc(wejscie *argp, struct svc_req *rqstp)
{
	static wyjscie  result;

	/*
	 * insert server code here
	 */
	char hex[512];
	int j = 0;
    int i = 0;
    while (argp->tekst[j] != '\0') {
		sprintf((char *) (hex + i), "%02X", argp->tekst[j]);
		j += 1;
		i += 2;
		}
	hex[i++] = '\0';

	printf("Otrzymany tekst: %s\n", hex);

	return &result;
}
